// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKpqEOn78fb4YKDk1ltm1x11XY9YCEvHU',
    appId: '1:384984468886:web:91de087a90465a0e71e1b7',
    messagingSenderId: '384984468886',
    projectId: 'maxatta-rt',
    authDomain: 'maxatta-rt.firebaseapp.com',
    storageBucket: 'maxatta-rt.firebasestorage.app',
    measurementId: 'G-LNMZSTTTN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuetNDIOmYdONQyq7n_y0N8mRb8CWxa3E',
    appId: '1:384984468886:android:dd66547424b2ca7d71e1b7',
    messagingSenderId: '384984468886',
    projectId: 'maxatta-rt',
    storageBucket: 'maxatta-rt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYVeCBt2f12APmKeXyPlqxKQ-rVyQ2fd8',
    appId: '1:384984468886:ios:54da29a23abe2f7471e1b7',
    messagingSenderId: '384984468886',
    projectId: 'maxatta-rt',
    storageBucket: 'maxatta-rt.firebasestorage.app',
    iosBundleId: 'com.example.maxattaRt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYVeCBt2f12APmKeXyPlqxKQ-rVyQ2fd8',
    appId: '1:384984468886:ios:54da29a23abe2f7471e1b7',
    messagingSenderId: '384984468886',
    projectId: 'maxatta-rt',
    storageBucket: 'maxatta-rt.firebasestorage.app',
    iosBundleId: 'com.example.maxattaRt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKpqEOn78fb4YKDk1ltm1x11XY9YCEvHU',
    appId: '1:384984468886:web:7a407a2e823d865b71e1b7',
    messagingSenderId: '384984468886',
    projectId: 'maxatta-rt',
    authDomain: 'maxatta-rt.firebaseapp.com',
    storageBucket: 'maxatta-rt.firebasestorage.app',
    measurementId: 'G-1X6M6KZ6V1',
  );
}
